OrdererOrgs:
  - Name: Orderer
    Domain: ord.ctfu.boc.cn
    EnableNodeOUs: false
    CA:
      Hostname: ca
      Country: CN
      Province: Beijing
      Locality: Beijing
      OrganizationalUnit: china-cba
    Template:
      Count: 1
PeerOrgs:
  - Name: Peer
    Domain: org.ctfu.boc.cn
    EnableNodeOUs: false
    CA:
      Hostname: ca
      Country: CN
      Province: Beijing
      Locality: Beijing
      OrganizationalUnit: china-cba
    Template:
      Count: 2
    Users:
      Count: 1
