version: '2'

services:
  api${NUM}.${CCNAME}:
    image: hub.finrunchain.com/fabric1.4/runchainapi:1.2.010.RELEASE
    container_name: api${NUM}.${CCNAME}
    restart: always
    working_dir: /opt/ApiServer
    environment:
      - LANG=en_US.UTF-8      
    volumes:
      - ./current.info:/opt/ApiServer/current.info
      - ./config:/opt/ApiServer/config
      - ./curl_scripts:/opt/ApiServer/curl_scripts
      - ../crypto-config:/opt/crypto-config    
      - ./logs:/opt/ApiServer/logs
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    ports:
      - ${API_PORT}:8888
    extra_hosts:
      orderer0.blockchain.ccb.com: ${LB_IP}
      orderer1.blockchain.ccb.com: ${LB_IP}
      orderer2.blockchain.ccb.com: ${LB_IP}
      peer0.blockchain.ccb.com: ${LB_IP}
      peer1.blockchain.ccb.com: ${LB_IP}
      peer2.blockchain.ccb.com: ${LB_IP}