spring:
  rabbitmq:
    username: loc
    password: loc
    addresses: ${MQ_ADDRESSES}
platform:
  component:
    apidoc.enable-swagger2: true
    blockchain:
      client:
        endorseConditions:
          - chaincode: fft
            matchOrgCount: 2
        cryptoType: SM2
        blockchainLedger1CallbackType: AMQP
        hyperledgerFabricSdkVersion: 1.4.0
        blockchainExchangeName: ${CCNAME}Queue
        invokeWaitTime: 32000
        deployWaitTime: 120000
        proposalWaitTime: 250000
        callbackServerName: api
        platformParams:
          channelName: channel${CCNAME}
          ordererOrganizationName: ${ORDERER_DOMAIN}
          peerOrganizationName: ${PEER_DOMAIN}
          businessCircleName: current.info
          username: User1@${PEER_DOMAIN}
        channels:
          - name: channel${CCNAME}
            cryptoConfigPath: /opt/crypto-config
            businessCircles:
            - name: current.info
              chaincodeName: ${CCNAME}
              chaincodePath: todo
              chaincodeVersion: 2.1.0
              chaincodeInputStream: todo
              chaincodeSourceLocation: 
              chaincodeEndorsementPolicyLocation: todo
              chaincodeLedgerVersion: 1.0.3
            ordererOrganizations:
            - name: ${ORDERER_DOMAIN}
              orderers:
              - name: orderer0.${ORDERER_DOMAIN}
                location: grpcs://orderer0.${ORDERER_DOMAIN}:${MYORDERER_7050}
                domain: ${ORDERER_DOMAIN}
            peerOrganizations:
            - name: ${PEER_DOMAIN}
              peers:
              - name: peer${NUM}.${PEER_DOMAIN}
                peerLocation: grpcs://peer${NUM}.${PEER_DOMAIN}:${PEER_7051}
                domain: ${PEER_DOMAIN}
              - name: peer${ENDORSER}.${PEER_DOMAIN}
                domain: ${PEER_DOMAIN}
                peerLocation: grpcs://peer${ENDORSER}.${PEER_DOMAIN}:${ENDORSER_7051}
                role:
                  endorsingPeer: true
                  ledgerQuery: false
                  chaincodeQuery: false
                  eventSource: false                
              admins:
              - name: Admin@${PEER_DOMAIN}
                enrollToken: todo
                mspid: ${PEER_MSP}
              users:
                - name: User1@${PEER_DOMAIN}
                  enrollToken: todo
                  mspid: ${PEER_MSP}
            - name: org.ctfu.china-cba.net
              peers:
              - name: peer0.org.ctfu.china-cba.net
                domain: org.ctfu.china-cba.net
                peerLocation: grpcs://peer0.org.ctfu.china-cba.net:7051
                role:
                  endorsingPeer: true
                  ledgerQuery: false
                  chaincodeQuery: false
                  eventSource: false
              - name: peer1.org.ctfu.china-cba.net
                domain: org.ctfu.china-cba.net
                peerLocation: grpcs://peer1.org.ctfu.china-cba.net:7751
                role:
                  endorsingPeer: true
                  ledgerQuery: false
                  chaincodeQuery: false
                  eventSource: false