spring:
  rabbitmq:
    username: loc
    password: loc
    addresses: ${MQ_ADDRESSES}
platform:
  component:
    apidoc.enable-swagger2: true
    blockchain:
      client:
        cryptoType: SM2
        blockchainLedger1CallbackType: AMQP
        hyperledgerFabricSdkVersion: 1.4.0
        blockchainExchangeName: ${CCNAME}Queue
        invokeWaitTime: 32000
        deployWaitTime: 120000
        proposalWaitTime: 120000
        callbackServerName: api
        platformParams:
          channelName: channel${CCNAME}
          ordererOrganizationName: ${ORDERER_DOMAIN}
          peerOrganizationName: ${PEER_DOMAIN}
          businessCircleName: current.info
          username: User1@${PEER_DOMAIN}
        channels:
          - name: channel${CCNAME}
            cryptoConfigPath: /opt/crypto-config
            businessCircles:
            - name: current.info
              chaincodeName: ${CCNAME}
              chaincodePath: todo
              chaincodeVersion: 2.0.0
              chaincodeInputStream: todo
              chaincodeSourceLocation: 
              chaincodeEndorsementPolicyLocation: todo
              chaincodeLedgerVersion: 1.0.3
            ordererOrganizations:
            - name: ${ORDERER_DOMAIN}
              orderers:
              - name: orderer0.${ORDERER_DOMAIN}
                location: grpcs://orderer0.${ORDERER_DOMAIN}:7050
                domain: ${ORDERER_DOMAIN}
            peerOrganizations:
            - name: ${PEER_DOMAIN}
              peers:
              - name: peer${NUM}.${PEER_DOMAIN}
                peerLocation: grpcs://peer${NUM}.${PEER_DOMAIN}:7051
                domain: ${PEER_DOMAIN}
              admins:
              - name: Admin@${PEER_DOMAIN}
                enrollToken: todo
                mspid: ${PEER_MSP}
              users:
                - name: User1@${PEER_DOMAIN}
                  enrollToken: todo
                  mspid: ${PEER_MSP}
              peers:
              - name: ${ENDORSE_PEER_ADDRESS}
                domain: org.${GENESIS_DOMAIN}
                peerLocation: grpcs://${GENESIS_PEER_ADDRESS}
                role:
                  endorsingPeer: true
                  ledgerQuery: false
                  chaincodeQuery: false
                  eventSource: false