PeerOrgs:
  - Name: ctfu
    Domain: ${DOMAIN}
    EnableNodeOUs: false
    CA:
        Country: CN
        Province: Beijing
        Locality: Beijing
    Specs:
      - Hostname: peer0
      - Hostname: peer1
      - Hostname: api0
      - Hostname: api1
    Users:
      Count: 1
OrdererOrgs:
  - Name: Orderer
    Domain: ${DOMAIN}
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      