version: '2'

services:
  peer-base:
    image: fabric-peer:ccb-1.4.4sm
    environment:
      # 强制指定节点容器内的域名解析为go，避免阿里云服务器将其转换为cgo
      - GODEBUG=netdns=go
      #--------------------
      # base env
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_fabric
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      # 设置是否使用GO profiling工具（一般开发测试环境为true，生产环境为false）
      - CORE_PEER_PROFILE_ENABLED=false
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_GOSSIP_RECONNECTMAXPERIOD=300
      - CORE_PEER_GOSSIP_RECONNECTMINPERIOD=5
      - CORE_PEER_GOSSIP_RECONNECTMINPERIODATTEMPTTIME=10
      # peer区块缓存大小
      - CORE_PEER_GOSSIP_DEFMAXBLOCKDISTANCD=200
      # 防止peer和event之间丢数
      - CORE_PEER_EVENTS_BUFFERSIZE=1000
      - CORE_PEER_EVENTS_TIMEOUT=0
      # Allow more time for chaincode container to build on install.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      # For runchain/ccenv
      - CORE_CHAINCODE_BUILDER=fabric-ccenv:ccb-1.4.4sm
      - CORE_CHAINCODE_NODE_RUNTIME=fabric-ccenv:ccb-1.4.4sm
      - CORE_CHAINCODE_GOLANG_RUNTIME=fabric-ccenv:ccb-1.4.4sm
      - FABRIC_LOGGING_SPEC=INFO
      # Enable operations server
      #- CORE_OPERATIONS_LISTENADDRESS=0.0.0.0:9443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    logging:
      driver: "json-file"
      options: 
        max-size: "50m"
        max-file: "10"
    volumes:
      - /var/run/:/host/var/run/
      - /etc/localtime:/etc/localtime

  cli-base:
    image: fabric-tools:amd64-1.4.4sm
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock      
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /etc/localtime:/etc/localtime
      - ../crypto-config:/etc/hyperledger/fabric/crypto-config
      - ../bin:/opt/gopath/src/github.com/hyperledger/fabric/peer/bin/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"